# version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: savorpalette-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    networks:
      - savorpalette-net

  db:
    image: mysql:8.0
    container_name: savorpalette-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - savorpalette-net

volumes:
  db_data:

networks:
  savorpalette-net:
