apiVersion: apps/v1
kind: Deployment
metadata:
  name: savorpalette-app
  namespace: savorpalette
spec:
  replicas: 2
  selector:
    matchLabels:
      app: savorpalette
  template:
    metadata:
      labels:
        app: savorpalette
    spec:
      containers:
        - name: savorpalette
          image: 728594302455.dkr.ecr.eu-west-1.amazonaws.com/savorpalette-app:latest
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
