name: Build and Push to ECR

on:
  push:
    branches: ["main"]

jobs:
  build-and-push:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          IMAGE_TAG=latest
          REPO_NAME=${{ secrets.ECR_REPOSITORY }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          docker build -t $REPO_NAME:$IMAGE_TAG .
          docker tag $REPO_NAME:$IMAGE_TAG $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$REPO_NAME:$IMAGE_TAG

      - name: Push Docker image to ECR
        run: |
          IMAGE_TAG=latest
          REPO_NAME=${{ secrets.ECR_REPOSITORY }}
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          docker push $ACCOUNT_ID.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/$REPO_NAME:$IMAGE_TAG
